# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Build sofle"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["sofle_left","sofle_right"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_MOUSE=y"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      alphas: '["QWERTZ"]'
      nav: '["vi"]'
      clipboard: '["Win"]'
      branches: '["zmkfirmware/zmk/main ftc/zmk/mouse-ftc"]'
